#Made by Darrien Drake
#Published on 20260903
#Please read the README.txt

class WordRoot:
    def Checker(Word, Term):

        WordA = {("no", "not", "without", "away from"): "a-",
                 ("away from", "negative", "absent"): "ab-",
                  "abdomen": "abdomin(o)-", 
                  "acetabulum (hip socket)": "acetabul(o)-",      
                 ("sound", "hearing"): ["acoust(o)-", "aud(i)-"],
                 ("tip", "peak", "extremity"): "acr(o)-",
                  "acromion": "acromi(o)-",
                 ("ray", "radiation"): "actin(o)-",
                 ("toward, to", "in the direction of"): "ad-",
                  "gland": "aden(o)-",
                 ("fat", "lipids"): "adip(o)-",
                  "adrenal gland": "adren(o)-",
                 ("air", "gas", "mist"): "aer(o)-",
                  "pain": ["alg(o)-", "algesi(o)-", "algi(o)-"],
                 ("nourishment", "food"): "aliment(o)-",
                  "male": "andr(o)-",
                 ("vessel", "blood vessel"): "angi(o)-",      
                 ("unequal", "dissimilar"): "anis(o)-",    
                 ("bent", "stiff", "crooked"): "ankyl(o)-",   
                  "anus": "an(o)-",     
                 ("front", "before"): "anter(o)-",       
                  "aorta": "aort(o)-",      
                  "apex": "apic(o)-",       
                 ("separate from", "derived from"): "ap(o)-",     
                  "appendix": "append(o)-",     
                  "water": ["aqu(i)-", "aqu(o)-", "aque(o)-"],       
                  "artery": "arteri(o)-",       
                  "joint": "arthr(o)-",     
                  "atlas": "atlant(o)-",        
                  "atrium": "atri(o)-",     
                  "ear": ["aur(i)-", "aur(o)-"],      
                  "armpit": "axill(o)-"}
    
        WordB = {"bacteria": "bacteri(o)-",        
                 "glans penis": "balan(o)-",       
                ("weight", "pressure"): "bar(o)-",     
                ("living organisms", "life"): "bi(o)-", 
                 "two, twice, double": ["bi-"],
                 "bile": "bil(i)-",        
                 "eyelid": "blephar(o)-",      
                 "arm": "brachi(o)-",
                 "short": ["brachy-"],
                 "slow": ["brady-"],
                ("bronchus", "bronchi"): "bronch(i)-",
                ("bronchiole", "bronchioles"): "bronchi(o)-", 
                 "cheek": "bucc(o)-"}

        WordC = {("heel", "calcaneus"): "calcane(o)-",
                   "calcium": "calci-",
                   "hair": "capill(o)-",
                   "head": "capit(o)-",
                   "cancer": "carcin(o)-",
                   "heart": "cardi(o)-",
                   "wrist": "carp(o)-",
                   "cartilage": ["chondr(o)-", "chondri(o)-"],
                   "cecum": "cec(o)-",
                   "abdomen": "celi(o)-",
                   "head": "cephal(o)-",
                   "cerebellum": "cerebell(o)-",
                   "brain": "cerebr(o)-",
                  ("neck", "cervix"): "cervic(o)-",
                   "lip": ["cheil(o)-", "chil(o)-"],
                   "hand": ["cheir(o)-", "chir(o)-"],
                   "chemical": "chem(o)-",
                   "green": "chlor(o)-",
                   "coccyx": "coccyg(o)-",
                   "cochlea": "cochle(o)-",
                   "colon": ["col(o)-", "colon(o)-"],
                   "vagina": "colp(o)-",
                   "dust": "coni(o)-",
                   "conjunctiva": "conjunctiv(o)-",
                   "feces": "copr(o)-",
                   "pupil": ["cor(o)-", "core(o)-"],
                   "coracoid process": "corac(o)-",
                   "heart": "cordi(o)-",
                   "cornea": "corne(o)-",
                   "cortex": "cortic(o)-",
                   "rib": "cost(o)-",
                   "skull": "crani(o)-",
                   "secrete": "crin(o)-",
                   "cold": "cry(o)-",
                   "hidden": "crypt(o)-",
                   "elbow": "cubit(o)-",
                   "skin": "cutane(o)-",
                   "blue": "cyan(o)-",
                  ("cyst", "bladder"): "cyst(o)-",
                   "cell": "cyt(o)-"}
        
        WordD = {"tears": "dacry(o)-",
                 "tear sac": "dacryocyst(o)-",
                ("finger", "toe"): "dactyl(o)-",
                 "lying down": "decubit(o)-",
                ("tooth", "teeth"): "dent(o)-",
                 "skin": ["derm(o)-", "dermat(o)-", "derma-"],
                 "right side": ["dextr(o)-"],
                ("two", "twice", "double"): "di-",
                 "sweat": "diaphor(o)-",
                 "diaphragm": "diaphragm(o)-",
                 "bone shaft (diaphysis)": "diaphys(o)-",  # from diaphysial/diaphyseal
                ("testis", "twins"): "didym(o)-",
                ("finger(s)", "toe(s)"): "digit(o)-",
                 "membrane": "diphther(o)-",
                 "double": "dipl(o)-",
                ("disk", "intervertebral disk"): ["disc(o)-", "disk(o)-"],
                 "back (of body)": ["dors(o)-", "dors(i)-"],
                 "duodenum": "duoden(o)-"}

        WordE = {"brain": "encephal(o)-",
                 "inside": ["end(o)-", "ent(o)-"],
                ("endocrine", "internal secretion"): "endocrin(o)-",
                 "endometrium": "endometr(o)-",
                 "endocardium": "endocardi(o)-",
                ("endocardium", "myocardium"): "endomyocardi(o)-",
                 "endosteum": "endoste(o)-",
                 "intestines": "enter(o)-",
                ("red", "rosy"): "eosin(o)-",
                 "epicardium": "epicardi(o)-",
                 "epicondyle": "epicondyl(o)-",
                 "epidermis": "epiderm(o)-",
                 "epididymis": "epididym(o)-",
                 "stomach region (epigastric)": "epigastr(o)-",
                 "epiglottis": "epiglott(o)-",
                 "esophagus": "esophag(o)-",
                 "female": "estr(o)-",
                 "sieve": "ethm(o)-",
                 "cause": "eti(o)-",
                 "rash": "exanthemat(o)-",
                 "external secretion": "exocrin(o)-",
                 "breathing out": ["expir(o)-", "expirat(o)-"],}
        
        WordF = {"fibrous tissue": "fibr(o)-",
                 "fiber": "fibr(o)-",
                 "thread": "fil(o)-",
                ("leaflike", "frond"): "frond(o)-",
                 "fever": "febr(i)-",
                 "fetus": "fet(o)-",
                 "thigh": "femor(o)-",
                 "iron": "ferr(o)-",
                 "fetus (alternate form)": "foet(o)-",
                ("split", "cleft"): "fiss(o)-",
                ("flame", "burning"): "flamm(o)-",
                 "flow": "fluor(o)-",
                 "leaf": "foli(o)-",
                ("form", "shape"): "form(o)-",
                 "fracture": "fract(o)-",
                 "fungus": "fung(i)-",
                 "smoke": "fum(o)-",
                ("furrow", "groove"): "foss(o)-"}
        
        WordG = {"stomach": "gastr(o)-",
                 "old age": "ger(o)-",
                ("origin", "production"): "gen(o)-",
                ("jaw", "cheek", "chin"): "geni(o)-",
                 "knee": "genu(o)-",
                 "tongue": "gloss(o)-",
                ("sugar", "glucose"): "gluc(o)-",
                ("sweetness", "sugar"): "glyc(o)-",
                ("glue", "gelatinous tissue"): "glutin(o)-",
                 "glial cells": "gli(o)-",
                ("ball", "sphere", "globe", "eyeball"): "glob(o)-",
                 "gluten": "gluten(o)-",
                ("woman", "female"): "gyn(o)-",
                 "female reproductive system": "gynec(o)-",
                 "pregnancy": "grav(i)-",
                ("record", "writing"): "graph(o)-",
                ("writing", "recording"): "gramm(o)-",
                ("grain", "particle"): "granul(o)-",
                 "jaw": "gnath(o)-",
                 "knowledge": "gnos(o)-"}

        WordH = {"blood": ["hemat(o)-", "haem(o)-"],
                 "liver": "hepat(o)-",
                 "tissue": ["hist(o)-", "histi(o)-"],
                ("moisture", "water"): "hydr(o)-",
                 "sleep": "hypn(o)-",
                ("same", "constant"): "home(o)-",
                ("other", "different"): "heter(o)-",
                ("same", "alike"): "hom(o)-",
                ("entire", "whole"): "hol(o)-",
                ("glass", "vitreous"): "hyal(o)-",
                 "sun": "heli(o)-",
                 "half": "hemi-",
                ("uterus", "womb"): "hyster(o)-",
                 "sweat": "hidr(o)-",
                 "snake": "herpet(o)-",                     
                 "sunlight": "heli(o)-",
                 "blood clot": "hem(o)-",
                 "entire": "hol(o)-"}

        WordI = {"ileum": "ile(o)-",
                 "ilium": "ili(o)-",
                 "iris": "irid(o)-",
                ("rainbow", "iris"): "ir(o)-",
                 "equal": "is(o)-",
                ("ischium", "hip"): "ischi(o)-",
                ("to hold back", "suppress"): "isch(o)-",
                 "fish": "ichthy(o)-",
                ("icon", "image"): "icon(o)-",
                 "fiber": "in(o)-",
                 "inflammation": "inflamm(o)-",
                 "intestine": "intestin(o)-",
                 "iris (alternate form)": "irid(o)-",
                ("same", "equal"): "iso-",
                 "ileum (alternate form)": "ile(o)-"}
        
        WordJ = {"jejunum": "jejun(o)-",
                 "joint": "junct(o)-",
                 "youth": "juven(i)-"}
        
        WordK = {"potassium": "kal(i)-",
                 "cornea": "kerat(o)-",
                ("movement", "motion"): "kinesi(o)-",
                 "nucleus": "kary(o)-",
                 "ketone bodies": "ket(o)-",
                ("horny tissue", "cornea"): "kerat(o)-",
                 "cell movement": "kines(o)-",
                 "to move": "kinet(o)-",
                 "pupil": "kore(o)-",
                 "pregnancy": "kye(o)-",   
                ("to steal", "seize"): "klept(o)-",
                 "cold": "kry(o)-",        
                 "hidden": "krypt(o)-"}

        WordL = {"milk": "lact(o)-",
                 "stone": "lith(o)-",
                 "white": "leuk(o)-",
                 "smooth": "lei(o)-",
                 "fat": "lip(o)-",
                 "side": "later(o)-",
                ("larynx", "voice box"): "laryng(o)-",
                 "lens of eye": "lent(i)-",
                 "ligament": "ligament(o)-",
                 "tongue": "lingu(o)-",
                 "lip": "labi(o)-",
                 "tear": "lacrim(o)-",
                ("lake", "fluid-filled space"): "lacun(o)-",
                ("lamina" , "thin plate"): "lamin(o)-",
                 "large intestine": "largeintestin(o)-",
                 "lobe": "lob(o)-",
                ("loins", "lumbar region"): "lumb(o)-",
                 "moon": "lun(o)-",
                 "light": "luc(i)-",
                 "yellow": "lute(o)-",
                 "wolf": "lyc(o)-",
                ("breakdown", "dissolve"): "lys(o)-",
                 "lymph": "lymph(o)-",
                 "fever": "lymphaden(o)-",
                ("loosen", "destroy"): "lytic(o)-"}

        WordM = {"breast": "mamm(o)-",
                 "breast (alternate form)": "mast(o)-",
                 "large": "macr(o)-",
                 "small": "micr(o)-",
                ("bad", "poor"): "mal(o)-",
                 "softening": "malac(o)-",
                ("spot", "stain"): "macul(o)-",
                 "madness": "man(i)-",
                 "hand": "manu(o)-",
                 "jaw": "maxill(o)-",
                 "middle": "mes(o)-",
                 "black": "melan(o)-",
                 "meninges": "mening(o)-",
                ("month", "menses"): "men(o)-",
                 "chin": "ment(o)-",
                 "mind": "ment(o)-",
                 "uterus": "metr(o)-",
                 "measure": "metr(o)-",
                ("change", "transformation"): "metamorph(o)-",
                 "middle (alternate form)": "medi(o)-",
                 "medulla": "medull(o)-",
                ("spinal cord", "marrow"): "myel(o)-",
                 "muscle": "my(o)-",
                 "fungus": "myc(o)-",
                 "mucus": "muc(o)-",
                 "slime": "myx(o)-",
                 "death": "mort(o)-",
                ("shape", "form"): "morph(o)-",
                 "movement": "mot(o)-",
                 "many": "mult(i)-",
                ("single", "one"): "mon(o)-",
                 "memory": "mnem(o)-",
                 "sleep": "morph(o)-",
                ("millipede", "thousand"): "mill(i)-"}
        
        WordN = {"nose": "nas(o)-",
                 "birth": "nat(o)-",
                 "nerve": "neur(o)-",
                 "new": "ne(o)-",
                 "kidney": "nephr(o)-",
                 "death": "necr(o)-",
                 "thread": "nemat(o)-",
                 "tendon": "neurotend(o)-",
                 "night": "nyct(o)-",
                 "cloudiness": "neb(o)-",
                ("nest", "cavity"): "nid(o)-",
                 "nine": "non(i)-",
                 "nucleus": "nucle(o)-",
                ("nutrient", "nourishment"): "nutri(o)-",
                 "nerve cell": "neuron(o)-",
                ("nest", "brood"): "nidus(o)-"}

        WordO = {("egg", "ovum"): "ov(o)-",
                "egg cell": "oocyt(o)-",
                "ear": "ot(o)-",
                "smell": "osm(o)-",
                "bone": "oste(o)-",
                ("straight", "correct"): "orth(o)-",
                "mouth": "or(o)-",
                "testis": "orch(o)-",
                "testicle": "orchi(o)-",
                "testes": "orchid(o)-",
                ("tumor", "mass"): "onc(o)-",
                "navel": "omphal(o)-",
                "shoulder": "om(o)-",
                ("few", "scanty"): "olig(o)-",
                ("all", "entire"): "omn(i)-",
                "dream": "oneir(o)-",
                "hook": "onych(o)-",
                ("claw", "nail"): "onych(o)-",
                "smell (alternate form)": "osphresi(o)-",
                "vision": "opt(o)-",
                "eye": "ophthalm(o)-",
                "snake": "ophidi(o)-",
                "tumor": "onc(o)-",
                "egg (alternate form)": "oo-",
                "back": "opisth(o)-",
                "serpent": "ophi(o)-"}

        WordP = {"disease": "path(o)-",
                ("feeling", "suffering"): "path(o)-",
                 "child": "pedi(o)-",
                 "foot": "pod(o)-",
                 "pressure": "press(o)-",
                 "digestion": "pept(o)-",
                 "fever": "pyret(o)-",
                 "pus": "py(o)-",
                ("heat", "fire"): "pyr(o)-",
                 "lung": "pneumon(o)-",
                ("air", "breath"): "pneum(o)-",
                 "mind": "psych(o)-",
                 "false": "pseud(o)-",
                 "many": "poly-",
                 "few": "pauci-",
                 "pelvis": "pelv(i)-",
                 "perineum": "perine(o)-",
                 "peritoneum": "peritone(o)-",
                 "pharynx": "pharyng(o)-",
                 "speech": "phras(o)-",
                 "vein": "phleb(o)-",
                ("love", "affinity"): "phil(o)-",
                 "fear": "phob(o)-",
                 "light": "phot(o)-",
                 "plant": "phyt(o)-",
                 "diaphragm": "phren(o)-",
                ("soul", "mind"): "pneum(o)-", 
                 "gray": "polio-",
                ("gatekeeper", "pylorus"): "pylor(o)-",
                 "itch": "prur(i)-",
                 "first": "prot(o)-",
                 "protein": "protein(o)-",
                 "pelvis (alternate form)": "pyel(o)-",
                 "hair": "pil(o)-",
                 "drink": "poto-",
                ("paint", "pigment"): "pigment(o)-",
                 "penis": "phall(o)-",
                 "voice": "phon(o)-",
                 "drug": "pharmac(o)-",
                ("eating", "swallowing"): "phag(o)-",
                 "lens": "phac(o)-",
                 "lens (alternate form)": "phak(o)-"}

        WordQ = {"four": "quadr(i)-",
                 "four (alternate form)": "quart(i)-",
                 "fifth": "quint(i)-",
                ("quivering", "trembling"): "quass(i)-",
                 "quality": "qualit(o)-",
                ("how much", "quantity"): "quant(i)-",
                ("quill", "spine"): "quill(o)-",
                 "to shake": "quati(o)-"}
        
        WordR = {("radiation", "x‑ray"): "radi(o)-",
                  "root": "radic(o)-",
                  "ray": "rad(i)-",
                  "wrinkle": "rhytid(o)-",
                 ("flow", "discharge"): "rrhe(o)-",
                  "nose": "rhin(o)-",
                  "network": "reticul(o)-",
                  "kidney": "ren(o)-",
                 ("net", "mesh"): "retinac(o)-",
                  "retina": "retin(o)-",
                  "straight": "rect(o)-",
                 ("fold", "ridge"): "ruga(e)-",
                  "branch": "ram(i)-",
                  "root (alternate form)": "rhiz(o)-",
                 ("rod", "stick"): "rhabd(o)-",
                  "rod‑shaped": "rhabdomy(o)-",
                 ("seam", "suture"): "raphe(o)-",
                  "scrape": "rasp(o)-",
                 ("burst", "rupture"): "rrhexis(o)-",
                  "flow": "rrhea(o)-"}

        WordS = {"sacrum": "sacr(o)-",
                 "flesh": "sarc(o)-",
                 "hard": "scler(o)-",
                 "curvature": "scoli(o)-",
                 "body": "somat(o)-",
                 "sleep": "somn(o)-",
                 "sound": "son(o)-",
                 "spasm": "spasm(o)-",
                 "spleen": "splen(o)-",
                ("vertebra", "spine"): "spondyl(o)-",
                 "scale": "squam(o)-",
                 "chest": "steth(o)-",
                 "narrowing": "sten(o)-",
                ("mouth", "opening"): "stom(at)(o)-",
                 "vertebra": "spondyl(o)-",
                 "seed": "sperm(at)(o)-",
                ("sphere", "globe"): "spher(o)-",
                 "wedge": "sphen(o)-",
                 "pulse": "sphygm(o)-",
                 "tube": "salping(o)-",
                 "salt": "salin(o)-",
                ("rotten", "decay"): "sapr(o)-",
                 "flesh (alternate form)": "sarco-",
                 "scale-like": "squam(o)-",
                ("split", "fissure"): "schiz(o)-",
                 "shadow": "sci(o)-",
                 "knowledge": "sci(o)-",
                ("crooked", "bent"): "scoli(o)-",
                 "body (alternate form)": "soma-",
                ("standing", "stopping"): "stasis(o)-",
                ("fat", "sebum"): "seb(o)-",
                ("infection", "poison"): "seps(o)-",
                ("rotting", "decay"): "septic(o)-",
                 "partition": "sept(o)-",
                 "serum": "ser(o)-",
                ("spine", "thorn"): "spin(o)-",
                 "breath": "spir(o)-",
                 "vertebra (alternate form)": "spondyl(o)-",
                 "scale (alternate form)": "squam(o)-",
                ("tight", "contracted"): "strict(o)-",
                ("stripe", "band"): "striat(o)-",
                 "structure": "struct(o)-",
                 "sugar": "sacchar(o)-",
                 "sweat": "sudor(o)-",
                 "together": "syn(o)-",
                ("union", "together"): "syndesm(o)-",
                ("syndrome", "running together"): "syndrom(o)-",
                 "symmetry": "symmetr(o)-"}

        WordT = {"heel": "tal(o)-",
                 "ankle": "tars(o)-",
                ("end", "limit"): "tel(o)-",
                ("end", "completion"): "teleo-",
                 "heat": "therm(o)-",
                ("place", "position"): "top(o)-",
                ("child", "growth"): "troph(o)-",
                 "nourishment": "troph(o)-",
                 "poison": "tox(o)-",
                 "poison (alternate form)": "toxic(o)-",
                ("cut", "incision"): "tom(o)-",
                 "birth": "toc(o)-",
                 "speed": "tach(o)-",
                ("fast", "rapid"): "tachy-",
                 "trachea": "trache(o)-",
                 "hair": "trich(o)-",
                 "clot": "thromb(o)-",
                 "thyroid gland": "thyroid(o)-",
                 "shield": "thyre(o)-",
                 "mind": "thym(o)-",
                 "death": "thanat(o)-",
                 "pressure": "tens(o)-",
                 "stretch": "tens(o)-",
                ("tone", "tension"): "ton(o)-",
                ("birth", "labor"): "toc(o)-",
                 "cheese": "tyr(o)-",
                 "pupil": "tympan(o)-",
                ("drum", "tympanum"): "tympan(o)-",
                 "tube": "tub(o)-",
                 "twisted": "tors(o)-",
                 "turning": "trop(o)-",
                ("reaction", "turning"): "tropism(o)-",
                 "tumor": "tumor(o)-",
                 "swelling": "tumefact(o)-"}

        WordU = {"ulna": "uln(o)-",
                 "ulcer": "ulcer(o)-",
                 "urine": "urin(o)-",
                 "urinary tract": "ur(o)-",
                 "ureter": "ureter(o)-",
                 "urethra": "urethr(o)-",
                 "uterus": "uter(o)-",
                 "uvula": "uvul(o)-",
                 "nail": "ungui(o)-",
                ("shade", "shadow"): "umbr(o)-",
                 "wave": "und(o)-",
                 "uric acid": "uric(o)-",}

        WordV = {"vagus nerve": "vag(o)-",
                 "wandering": "vag(o)-",
                 "valve": "valv(o)-",
                 "valve (alternate form)": "valvul(o)-",
                 "vein": "ven(o)-",
                ("venom", "poison"): "venen(o)-",
                 "ventricle": "ventricul(o)-",
                ("belly", "abdomen"): "ventr(o)-",
                ("turn", "roll"): "vers(o)-",
                 "vertebra": "vertebr(o)-",
                 "bladder": "vesic(o)-",
                ("small bladder", "vesicle"): "vesicul(o)-",
                 "vessel": "vas(o)-",
                ("duct", "vessel"): "vascul(o)-",
                 "vulva": "vulv(o)-",
                ("hairy", "shaggy"): "vill(o)-",
                 "virus": "vir(o)-",
                 "green": "virid(o)-",
                 "glass": "vitre(o)-",
                 "life": "vit(o)-",
                 "voice": "voc(o)-",
                ("to call", "voice"): "voc(i)-",
                 "turning": "volv(o)-",
                 "to roll": "volut(o)-"}

        WordW = {"windpipe": "windpip(o)-",
                 }

        WordX = {"dry": "xer(o)-",
                ("foreign", "strange"): "xen(o)-",
                 "yellow": "xanth(o)-",
                 "wood": "xyl(o)-",
                 "sword": "xiph(o)-",
                 "host": "xen(o)-",
                 "dryness": "xer(o)-"}
        
        WordY = {}
        
        WordZ = {"animal": "zo(o)-",
                ("ferment", "enzyme"): "zym(o)-",
                ("yoke", "join"): "zyg(o)-",
                ("belt", "girdle"): "zoster(o)-",
                 "life (rare form)": "zoe(o)-",
                 "living being": "zoon(o)-",
                 "fermentation (alternate form)": "zym(i)-",
                ("pair", "union"): "zygomat(o)-",
                 "fermenting organism": "zym(o)-"}
        
    

        merged = {}
        for d in (WordA, WordB, WordC, WordD, WordE, WordF, WordG, WordH,
                  WordI, WordJ, WordK, WordL, WordM, WordN, WordO, WordP,
                  WordQ, WordR, WordS, WordT, WordU, WordV, WordW, WordX,
                  WordY, WordZ):
            merged.update(d)

        # Build normalized lookup indexes (meaning -> prefixes, prefix -> meanings)
        meaning_to_combining_form = {}
        combining_form_to_meaning = {}

        def normalize_meanings(key):
            if isinstance(key, tuple):
                return [k.strip().lower() for k in key]
            if isinstance(key, str) and ',' in key:
                return [k.strip().lower() for k in key.split(',')]
            return [str(key).strip().lower()]

        def normalize_combining_forms(val):
            if isinstance(val, list):
                return [str(v).strip().lower() for v in val]
            return [str(val).strip().lower()]

        for key, val in merged.items():
            meanings = normalize_meanings(key)
            combining_forms = normalize_combining_forms(val)
            for m in meanings:
                meaning_to_combining_form.setdefault(m, []).extend(combining_forms)
            for c in combining_forms:
                combining_form_to_meaning.setdefault(c, []).extend(meanings)

        # Lookup (fast, single pass)
        if Term in meaning_to_combining_form:
            res = meaning_to_combining_form[Term]
            print(f"{Term} Combining form is {res}")
            return res[0] if len(res) == 1 else res
        if Term in combining_form_to_meaning:
            res = combining_form_to_meaning[Term]
            print(f"{Term} is the Combining form of {res}")
            return res[0] if len(res) == 1 else res

        raise KeyError(f"'{Term}' is not considered a Combining form")
